### ISSUE TITLE
GitHub URI not recognized in plugin header

### ISSUE THREAD

**Issue by NateWr** [FacetWP/github-updater-lite#10]
Have you run into any issues where the `GitHub URI` plugin header is not getting picked up? I'm trying to integrate this but I've found that the GitHub URI key is not a part of `$info` on this line:

https://github.com/FacetWP/github-updater-lite/blob/master/github-updater.php#L49

My plugin header, which is at `/wp-content/plugins/totc-layout-control/totc-layout-control.php` is the following:

```php
<?php
/**
 * Plugin Name: Theme of the Crop Layout Control
 * Plugin URI: https://themeofthecrop.com
 * Description: Beautiful homepage layouts for themes from Theme of the Crop.
 * Version: 0.1.0
 * Author: Theme of the Crop
 * Author URI: https://themeofthecrop.com
 * License:     GNU General Public License v2.0 or later
 * License URI: http://www.gnu.org/licenses/gpl-2.0.html
 * GitHub URI: NateWr/totc-layout-control
 *
 * Text Domain: totc-layout-control
 * Domain Path: /languages/
 *
 * This program is free software; you can redistribute it and/or modify it under the terms of the GNU
 * General Public License as published by the Free Software Foundation; either version 2 of the License,
 * or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
 * even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * You should have received a copy of the GNU General Public License along with this program; if not, write
 * to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
 */
defined( 'ABSPATH' ) || exit;

// ...
```

Am I missing something obvious here?

**Comment by afragen** [comment]
It currently doesn't appear that this header is on the upstream code.

**Comment by NateWr** [comment]
@afragen Do you mean it's not yet on the `master` branch at GitHub? That's correct. Does it need to be? I planned to test the integration before committing it.

**Comment by afragen** [comment]
It should show an update if the version number is lower. Having the header locally should be enough to check and find an update. 

I wrote to GitHub Updater plugin but I believe Matt designed it similarly.

**Comment by afragen** [comment]
But looks Ok otherwise.

**Comment by mgibbs189** [comment]
@NateWr can't say that I have...

FWIW, the update check runs every 12 hours by default. If the tag was created *after* the last check, you may need to manually remove the `ghu_last_checked`wp_option or use the `ghu_check_interval` hook to temporarily set it lower.

**Comment by NateWr** [comment]
I tracked the issue down to the load order. I was loading the github updater in the `plugins_loaded` action, so the extra header was not getting registered until after the plugin data has been collected.

The following PR just adds a note about this to the readme:

https://github.com/FacetWP/github-updater-lite/pull/11
