### ISSUE TITLE
Fork to pull from release binaries instead of tags

### ISSUE THREAD

**Issue by NateWr** [FacetWP/github-updater-lite#12]
Thanks for this helpful lib! Just a heads-up that I forked it to pull from release binaries instead of tags, since my plugin has build steps and isn't ready-to-use straight from the repository.

That's in a `totc` branch in my fork here if you want to see:

https://github.com/NateWr/github-updater-lite/tree/totc

:tumbler_glass: Cheers!

**Comment by mgibbs189** [comment]
Thanks for the heads-up.

**Comment by Rarst** [comment]
Any interest in getting that merged here? The logic could be first look for release, fall back to source.

Different updaters in the wild running off the same header will conflict eventually.
