### ISSUE TITLE
Update all active plugins?

### ISSUE THREAD

**Issue by herrvigg** [FacetWP/github-updater-lite#14]
I tried this and i'm bit confused how you intend to install this. Is it for a single plugin or globally for all plugins? In the readme you write copy it to your `plugin folder` and include it from your main plugin file. So i understand it's more for a single plugin and that's actually how i would like to use it. But the problem is it checks all active plugins, not only the current one it's installed in... 

I think it's very bad idea to go and check all active plugins if this is installed in a single plugin, you shouldn't disturb how the other plugins are updating themselves. On the other hand if it's meant to be used for all plugins the documentation is not clear enough.

**Comment by herrvigg** [comment]
Here are a few precisions after trying it out:

- The original project githut-updated is packaged as a separate plugin. It makes sense that it tests all plugins.

- However this Lite project to me is rather meant to be fully integrated in an existing plugin, rather than being a "Lite separate plugin". As a consequence it should only check the plugin it's handling, absolutely not all the other plugins! This can potentially create a lot of side effects and integration issues. For example, both projects (full plugin and lite version) could interfer between themselves. This project can even potentially interfer with itself, if the class is duplicated in multiple plugins...

Therefore it should be better packaged for individual use. The fact that it uses "Github URI", while only supporting short format owner/repo is also confusing. Since other projects have "Github Plugin URI" it should use the same or clearly define a separate field for own auto udpate. 
Also, some hooks can probably be removed and this project can possibly be simplified even more.

**Comment by mgibbs189** [comment]
The library scans for all plugins with the "GitHub URI" tag. I'm not sure why all concern, it's very little overhead and doesn't require any additional file scans over what WP already loads.

**Comment by herrvigg** [comment]
You shouldn't close this ticket. The problem is not the overhead but side effects. Since this is not a plugin to handle all plugins, it should not go and impact other plugins it's not supposed to handle. It's really a very bad practice! This will go and impact how other plugins are updated since you are writing in the site transient. Wordpress should never allow that but the whole framework with the hooks allow so many hack... This is why the integration is such a mess.

**Comment by mgibbs189** [comment]
Again, it doesn't impact other plugins unless the author has **explicitly** added the `GitHub URI` tag into their plugin's description.

**Comment by herrvigg** [comment]
Again, i think it should definitely not do that unless it is a real plugin that handles all the plugins on an installation. Here i understand this file should be copied in a given plugin so why would you impact the others?? It doesn't make sense. If this is intended to work this way, the documentation is not clear enough.
