### ISSUE TITLE
plugin_information not retrieved

### ISSUE THREAD

**Issue by herrvigg** [FacetWP/github-updater-lite#15]
All the information about the last available version is not processed correctly, you get a nasty error message instead. 

I debugged the code and the reason is you mix up internally the "plugin path" and the "plugin slug". What you call "slug" when looking for `active_plugins` or `get_plugins` is not the slug but the plugin path (relative). Yes it's very poorly defined in Wordpress... and i'm not sure it would work well for singe-file plugins that are not installed in a folder. Many assume there is a folder for every plugin.

But at least for standard plugins in a folder i made a hotfix that works, i'll try to send it later through a PR.

**Comment by mgibbs189** [comment]
This is meant for plugins that are contained within their own folder. The "lite" part means that the lib makes a handful assumptions... one if which being that the plugin is *not* a single, folderless file.

**Comment by herrvigg** [comment]
Why do you close this ticket? I even sent you a fix and you haven't checked well. I don't even understand how the plugin info can be displayed, there's no chance the slug will match the plugin file (directory/plugin.php). What Wordpress are you using?
