### ISSUE TITLE
plugin_information override

### ISSUE THREAD

**Issue by herrvigg** [FacetWP/github-updater-lite#16]
Though the plugin info is not processed i also point out some strange things in the code:

                            'requires'      => '4.7',
                            'tested'        => get_bloginfo( 'version' ),
                            'last_updated'  => date( 'Y-m-d' ),

Why would you enforce the WP version of the plugin to 4.7 here? I don't understand this at all.
Why do you return the tested version as the current version of the blog? It has nothing to do with the plugin info.
Why is the last update the current date? It's wrong.

It looks wrong to me. Better not display anything than confusing information.

**Comment by mgibbs189** [comment]
Those are just defaults. We could add a hook to customize the defaults if needed. Or you could just modify the library itself to suit your needs.

**Comment by herrvigg** [comment]
What default? Here it will display some data that has nothing to do with the current plugin.
Sorry but it seems you are not very willing to update your stuff...
