### ISSUE TITLE
Github Rate Limiting not as restrictive as you think...

### ISSUE THREAD

**Issue by blogtutor** [FacetWP/github-updater-lite#20]
Hey @mgibbs189 I tried emailing you at facetwp.com, but it bounced back, so I figured I'd just open an issue here.

Just wanted to mention something I noticed over the weekend in the Github API docs.  The rate limiting of 60 requests/hour is based on the client that's making the request (not the repo).  So I'm thinking that as long as the updater plugin doesn't make a call to the API on every pageload in the dashboard, it would be unlikely to hit those limits for any given site.
 
https://developer.github.com/v3/#rate-limiting

> For unauthenticated requests, the rate limit allows for up to 60 requests per hour. Unauthenticated requests are associated with the originating IP address, and not the user making requests. 

I added an API call to display the Changelog in the "View Details" window (by retrieving the Releases info and formatting it nicely); that shouldn't cause a problem with rate limiting because it's only called once someone clicks "View Version x.x.x Details"... and they're not going to do that 60 times an hour. (I also coded it so that if the API returns a 403, it'll show a fallback that links to the webpage of the Releases instead.)

At the moment, the only part of my code that wouldn't work automatically for everyone is that I've hardcoded the $owner/$repo part of the API url.. since those variables were created in a different function and not already available. But if we get that part working, this could be added to the plugin so everyone could benefit from automatic changelog generation.

Just trying to help out here and give back a little, since you (and this code library!) have been so helpful! :)

Thanks,
Andrew

**Comment by afragen** [comment]
So here’s the real problem of trying to maintain an _lite_ product and added features. In order to parse a readme.txt file you need to include a parser. In order to parse a change log you will like need a Markdown parser. 

BTW you’ll need the Markdown parser for the readme parser too.

**Comment by blogtutor** [comment]
Hey Andy, thanks for jumping in.  Right now it's pretty simple -- I'm having it parse the API response for the Github "Releases" page. (So it's not dealing with a readme.txt or anything.)

The code below is what I implemented... it's working great, and I think the only thing we'd need to do to include this in the Lite file so that it can work for everyone is get rid of my hardcoded API URL and replace it with those $owner/$repo variables. (And remove my hardcoded header image references, of course!).  :)

```
  function plugins_api( $default = false, $action, $args ) {
            if ( 'plugin_information' == $action ) {
                foreach ( $this->update_data as $plugin_path => $info ) {
                    if ( $info['slug'] == $args->slug ) {

                      $changelog_url = 'https://api.github.com/repos/blogtutor/blog-tutor-support/releases';
                      $changelog = wp_safe_remote_get( esc_url_raw( $changelog_url ) );
                      $changelog_output = '';

                      // Check that API responded okay, else use a fallback link.
                      if ( ! is_wp_error( $changelog ) && wp_remote_retrieve_response_code( $changelog ) == '200' ) {
                        $changelog = json_decode( wp_remote_retrieve_body( $changelog ), true );
                        // Parse and format the Github API Response
                        foreach ( $changelog as $note => $release_note ) {
                          $changelog_output .= '<h4>' . $changelog[$note]['tag_name'] . ' - ' . date ( "F j, Y", strtotime( $changelog[$note]['published_at'] ) ) . '</h4>';
                          $changelog_output .= '<p>' . $changelog[$note]['name'] . '</p>';
                          if ( $changelog[$note]['body'] != '' ) {
                            $changelog_output .= '<blockquote>' . nl2br( $changelog[$note]['body'] ) . '</blockquote>';
                          }
                        }
                      } else {
                        $changelog_output = '<a href="https://github.com/blogtutor/blog-tutor-support/releases" target="_blank">View the changelog here</a>.';
                      }

                      return (object) array(
                          'name'          => $info['name'],
                          'slug'          => $info['slug'],
                          'version'       => $info['new_version'],
                          'download_link' => $info['package'],
                          'sections' => array(
                              'description' => $info['description'],
                              'changelog' =>  $changelog_output
                          ),
                          'banners' => array(
                              'low' => 'https://www.nerdpress.net/wp-content/uploads/2019/01/nerdpress-support-plugin-header-small.jpg',
                              'high' => 'https://www.nerdpress.net/wp-content/uploads/2019/01/nerdpress-support-plugin-header-large.jpg'
                          )
                      );
                    }
                }
            }

            return $default;
        }

```

**Comment by afragen** [comment]
Remember for your use case narrowly defining how the changes are formatted is required. It’s a different story when trying to ensure it works everywhere. 

You don’t need to have a change log or an API call if you simply want a basic View Details link. See previous issue and my reference to stuff in GitHub Updater.

**Comment by blogtutor** [comment]
Right... except I _did_ want a changelog, and I found that by querying the API for the existing "Releases" information (which is already required to use Github Updater Lite), I could get a nice-looking changelog without having to do any additional work at the time of release. No text file to maintain or update separately, etc.

Regarding formatting -- Won't the formatting of the changelog info be the same for everyone using Github Updater Lite, since it's all going to be on the "Releases" page, like this one?

https://github.com/blogtutor/blog-tutor-support/releases

(Since everyone needs to use the "Releases" function to create the tags and cause an update... so it's already standardized.)

If you guys aren't interested in incorporating this into the Lite plugin, that's totally cool... I'm just throwing it out there in case it's helpful.

That, and my point above about the API request limits not being as strict as @mgibbs189 seems to think.  ;)

**Comment by afragen** [comment]
You don’t need to use the releases function to create a tag.

**Comment by afragen** [comment]
This is totally Matt’s project. I simply pop in to share my experiences. 😉

**Comment by blogtutor** [comment]
> You don’t need to use the releases function to create a tag.

Ah, good point. I've been using "Releases" since we started and forgot that it's really just tags that are mandatory.  I suppose it would be pretty easy to add a check to see if there are any actual releases, and only include the changelog if so.

**Comment by mgibbs189** [comment]
Wow, there's a lot to process here 😆 

@blogtutor most sites _probably_ won't hit the limit. That said, I've seen sites with over a dozen GHU-powered plugins, so it could be a tight rope... especially if any dev has customized the `ghu_check_interval`. 

@afragen right, this lib isn't meant to be everything to everyone. A changelog would be nice -- but not critical -- especially since it currently requires that extra API call. I sure wish GitHub would either up their limit, or allow some unauthenticated v4 requests 🙁 

Also worth noting that these update checks do have hidden costs. I'm sure you've logged into sites to find the dashboard initially taking 5-10 seconds to load. This is because all plugins are doing their update checks at once. Each GitHub API call usually takes anywhere from 0.1 - 0.4s, and if you have 10-15 GHU plugins installed, that can really add up.

@afragen is also right that `tag !== release`. A release is a GitHub-specific feature. Many repos aren't actually using releases.

@blogtutor would it help if we added a hook to let you modify [the return object here](https://github.com/FacetWP/github-updater-lite/blob/master/github-updater.php#L93-L101)?

**Comment by blogtutor** [comment]
One thing I noticed is that the API request I'm making to generate the changelog doesn't actually happen until someone clicks the "View details" (or "View version x.x.x details") link. 

At this point I'm likely to just stick with what I've got set up, rather than refactoring to work with a hook. But I could definitely see how a hook would have been useful/welcome!  :)

The other thing I want to be sure we don't lose in this conversation is that the "View Details" link still only shows up when an update is showing as available. Ideally, "View Details" should always be there, shouldn't it?  (If you'd like, I'm happy to open that as a new/separate issue?)

**Comment by mgibbs189** [comment]
@blogtutor IMO the "View Details" issue is a WP core bug. Third-party plugins _should_ show that just like wp.org plugins.

I'm not adding it into this lib, but time-permitting it might be worth investigating the possibility of a WP core patch.

@afragen's [hook](https://github.com/FacetWP/github-updater-lite/issues/19#issuecomment-455381791) is the best current solution, but frankly I don't like how it's even necessary.
