### ISSUE TITLE
Throws a notice when installing another plugin

### ISSUE THREAD

**Issue by robneu** [FacetWP/github-updater-lite#4]
![screen shot 2016-06-23 at 9 43 06 pm](https://cloud.githubusercontent.com/assets/2184093/16325404/c05eadd6-398b-11e6-83d0-760dc03c25c2.jpg)

This is from the version of the library in the latest version of FacetWP, so you may have already fixed this. At a quick glance, it looks like you just need an `isset` check for `$hook_extra['plugin']` before continuing.

**Comment by afragen** [comment]
Just curious but what version of WP is installed?

$hook_extra wasn't defined until WP 4.4

**Comment by robneu** [comment]
4.5.2

**Comment by afragen** [comment]
Hmm. I didn't think you were less than 4.4 but I had to ask. 

Quick solution would be to return early `if empty($plugin)`

What were the circumstances of the error? I don't have FacetWP installed but trying to figure out how to test.

**Comment by robneu** [comment]
Steps to reproduce are:

Install and activate FacetWP
Install another plugin from the .org repo

If you're running xdebug, you should see the notice on screen just before the plugin activation text. Without xdebug, you'd probably have to check logs to see it.

**Comment by afragen** [comment]
#5 should fix this

**Comment by robneu** [comment]
FWIW, this also works:

``` php
if ( empty( $hook_extra['plugin'] ) ) {
    return $source;
}
```

**Comment by afragen** [comment]
Yes, but it's more lines. 😉

**Comment by robneu** [comment]
Meh, it's one less function call and easier to read.

**Comment by afragen** [comment]
How about latest revision? No additional function calls.

**Comment by robneu** [comment]
Haha 👍

**Comment by mgibbs189** [comment]
What a great thing to wake up to :) Thank you both for addressing!
