### ISSUE TITLE
Use Composer Autoloader

### ISSUE THREAD

**Issue by schlessera** [FacetWP/github-updater-lite#7]
I recommend adding Composer autoloader support to this package, using the `"files"` directive of the autoloader.

The effect depends on how the package is being pulled in:

1. Site-wide Composer stack: Site loads site-wide autoloader, GHU is automatically active.
2. Plugin-local Composer installation: Plugin loads plugin-local autoloader, GHU is automatically active. Can be overridden by 1. as needed.
3. No Composer: Plugin `include`s file manually, works just as it does now.

**Comment by schlessera** [comment]
Benefit for Composer users:

* They don't need to care about where the `github-updater.php` file is located (no hard-coding of paths/filenames).
* If the package changes to a different architecture with a real class-based autoloader later on, no changes are necessary for Composer users.

**Comment by mgibbs189** [comment]
Thanks @schlessera, merged
